#install.packages("RMySQL")
#install.packages("DBI")
library(RMySQL)
db=dbDriver("MySQL")
db1=dbConnect(db,user="root",dbname="shipment",host="localhost")
a=dbListTables(db1)
print(a)
b=dbSendQuery(db1,"select * from shipment")
r=print(b)
v=fetch(r,n=5)
print(v)
