library(ggplot2)
library(plotly)
setwd("C:/Users/a2fsh/Desktop/My DS programms")
zoo <- read.csv("zoo.csv",stringsAsFactors = FALSE)
attach(zoo)
zoo=zoo[1:(ncol(zoo)-2)]
zoo=zoo[which(animal_name!='girl'),]
#View(zoo)
print(zoo)

p=ggplot(zoo,aes(animal_name,hair))+geom_bar(stat='identity')+theme_bw()+ggtitle("Graph 1.1")
ggplotly(p)
p=ggplot(zoo,aes(animal_name,feathers))+geom_bar(stat='identity')+theme_bw()+ggtitle("Graph 1.2")
ggplotly(p)
p=ggplot(zoo,aes(animal_name,eggs))+geom_bar(stat='identity')+theme_bw()+ggtitle("Graph 1.3")
ggplotly(p)
p=ggplot(zoo,aes(animal_name,milk))+geom_bar(stat='identity')+theme_bw()+ggtitle("Graph 1.4")
ggplotly(p)
p=ggplot(zoo,aes(animal_name,airborne))+geom_bar(stat='identity')+theme_bw()+ggtitle("Graph 1.5")
ggplotly(p)
p=ggplot(zoo,aes(animal_name,aquatic))+geom_bar(stat='identity')+theme_bw()+ggtitle("Graph 1.6")
ggplotly(p)
p=ggplot(zoo,aes(animal_name,predator))+geom_bar(stat='identity')+theme_bw()+ggtitle("Graph 1.7")
ggplotly(p)
p=ggplot(zoo,aes(animal_name,toothed))+geom_bar(stat='identity')+theme_bw()+ggtitle("Graph 1.8")
ggplotly(p)
p=ggplot(zoo,aes(animal_name,backbone))+geom_bar(stat='identity')+theme_bw()+ggtitle("Graph 1.9")
ggplotly(p)
p=ggplot(zoo,aes(animal_name,breathes))+geom_bar(stat='identity')+theme_bw()+ggtitle("Graph 1.10")
ggplotly(p)
p=ggplot(zoo,aes(animal_name,venomous))+geom_bar(stat='identity')+theme_bw()+ggtitle("Graph 1.11")
ggplotly(p)
p=ggplot(zoo,aes(animal_name,fins))+geom_bar(stat='identity')+theme_bw()+ggtitle("Graph 1.12")
ggplotly(p)
p=ggplot(zoo,aes(animal_name,legs))+geom_bar(stat='identity')+theme_bw()+ggtitle("Graph 1.13")
ggplotly(p)
p=ggplot(zoo,aes(animal_name,tail))+geom_bar(stat='identity')+theme_bw()+ggtitle("Graph 1.14")
ggplotly(p)
p=ggplot(zoo,aes(animal_name,domestic))+geom_bar(stat='identity')+theme_bw()+ggtitle("Graph 1.15")
ggplotly(p)

print("Total number of missing values (NA) in the zoo.")
print(sum(is.na(zoo)))

print("Total number of animals which both milks and lay eggs.")
print(sum(milk==eggs))
print("Name of animals which both milks and lay eggs.")
print(zoo[which(milk==eggs),"animal_name"])

print("Total number of animals which are predators.")
print(sum(predator))
print("Name of animals which are predators(need to be supervised and visitors should not come near).")
print(zoo[which(predator==TRUE),"animal_name"])

print("Total number of aquatic animals which are predators(need to be supervised and warnings must be issued to visitors).")
print(sum(predator & !aquatic))
print("Aquatic animals which are predators(need to be supervised and warnings must be issued to visitors).")
print(zoo[which(predator & !aquatic),"animal_name"])

print("Total number of animals which are airborne(need to have cages according to their size.")
print(sum(airborne))
print("Name of animals which are airborne(need to have cages according to their size.")
print(zoo[which(airborne==TRUE),"animal_name"])

print("Total number of animals which are predators(need to have both aquatic aerial equiped cages).")
print(sum(airborne & aquatic))
print("Animals which are predators(need to have both aquatic aerial equiped cages).")
print(zoo[which(airborne & aquatic),"animal_name"])

print("Total number of animals which require an Aquarium.")
print(sum(aquatic & fins & !breathes))
print("Name of animals which require an Aquarium.")
print(zoo[which(aquatic & fins & !breathes),"animal_name"])

print("Total number of animals which require an aquatic habitat but require an open roof as they have to come to surface to breath.")
print(sum(aquatic & fins & breathes))
print("Name of animals which require an aquatic habitat but require an open roof as they have to come to surface to breath.")
print(zoo[which(aquatic & fins & breathes),"animal_name"])

print("Total number of animals which are poisnous(need to be supervised and warnings must be issued to visitors).")
print(sum(venomous & !aquatic))
print("Animals which are poisnous(need to be supervised and warnings must be issued to visitors).")
print(zoo[which(venomous & !aquatic),"animal_name"])

print("Total number of animals which are poisnous(need to be supervised(experts required) and warnings must be issued to visitors).")
print(sum(venomous & aquatic))
print("Animals which are poisnous(need to be supervised(experts required) and warnings must be issued to visitors).")
print(zoo[which(venomous & aquatic),"animal_name"])

print("Total number of animals which are domestic(need to be kept away from wild animals)")
print(sum(domestic))
print("Animals which are domestic(need to be kept away from wild animals)")
print(zoo[which(domestic==TRUE),"animal_name"])