a=matrix(1:6,nrow=2,ncol=3,dimnames=list(c('r1','r2'),c('c1','c2','c3')))
#dimnames(a)=list(c('r1','r2'),c('c1','c2','c3'))
print(dimnames(a))
print(paste("No. of rows is:",nrow(a)))
print(paste("No. of cols is:",ncol(a)))
print("Matrix element (1,3)")
print(a[1,3])
print("Matrix full")
print(a)
print("Matrix row 1")
print(a[1,])
print("Matrix col 3")
print(a[,3])
a[1,3]=9
print(paste("Matrix updated element (1,3) is",a[1,3]))
a=rbind(a,r3=c(7,8,5))
a=cbind(a,c4=c(10,11,12))
print("Matrix full after adding row and column")
print(a)
b=matrix(1:12,nrow=3,ncol=4,byrow=TRUE,dimnames=list(c('r1','r2','r3'),c('c1','c2','c3','c4')))
print("Another matrix")
print(b)
a=a+b
print("Matrix full after adding another matrix to it")
print(a)
a=a-b
print("Matrix full after subtracting back another matrix from it")
print(a)
a=a*b
print("Matrix full after multiplying another matrix from it")
print(a)
a=a/b
print("Matrix full after dividing back another matrix from it")
print(a)
print(paste("Matrix test A",is.matrix(a)))
print(paste("Matrix test B",is.matrix(b)))
print(paste("Sum of row 1 of Matrix A",sum(a[1,])))
print(paste("Mean of col 1 of Matrix A",mean(a[,1])))